version: "3"
services:
  nginx:
    image: nginx
    container_name: 13301_web
    ports:
      - "13301:80"
    links:
     - php
     - database
    volumes:
      - ./server.conf:/etc/nginx/nginx.conf:ro
      - ./site.conf:/etc/nginx/conf.d/default.conf:ro
      - ../src:/var/www/html

  php:
    build: ./php-fpm-composer
    container_name: 13302_php
    ports:
      - "13302:9000"
    volumes:
      - ../src:/var/www/html

  database:
    image: mariadb:latest
    container_name: 13303_db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=drupal8
    ports:
      - "3308:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - 13303:8080
